
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines-bz

pool:
 vmImage: 'ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
  displayName: Use Python 3.6

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- script: 
     python scripts/generate_conda_file.py --gpu
  displayName: ' generate_conda_file.py'

- script: |
    conda env create -n reco_gpu -f ./reco_gpu.yaml 
  displayName: 'create conda env3'

- script: |
     chmod +x scripts/*.py
     ls -al scripts
  displayName: 'ls'

#- task: PythonScript@0
#  inputs:
#    targetType: 'inline'
#    script: |
#      print('Hello world 1')
#      print('Hello world 2')
#  displayName: ' Python Script'
  
#- bash: |
#    conda env list
#    source activate reco_gpu
#    pytest --version
#    python -c "import azureml.core; print("SDK version:", azureml.core.VERSION)"
#    pytest tests/unit/test_gpu_utils.py::test_get_number_gpus
#  displayName: 'unit tests'

- task: AzureCLI@1
  displayName: 'Create or get workspace'
  inputs:
    azureSubscription: 'AzureML Nursery (15ae9cb6-95c1-483d-a0e3-b1a1a3b06324)'
    scriptLocation: inlineScript
    inlineScript: 'python scripts/00-WorkSpace.py'

#- task: PythonScript@0:
##  inputs:
#    targetType: 'inline'
#    script:
#      ws = Workspace(subscription_id = 15ae9cb6-95c1-483d-a0e3-b1a1a3b06324, resource_group = 'recommender', workspace_name = 'RecoWS')
#    echo "$BUILD_REPOSITORY_LOCALPATH"
#    ls

#  displayName: ' set up ws'

#- script: 
#     python scripts/AzureDevOps.py
#  displayName: ' test_aml_compute'

