
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#
#

trigger:
- azure-pipelines-bz

pool:
 vmImage: 'ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
  displayName: Use Python 3.6

- bash: |
    echo "##vso[task.prependpath]/data/anaconda/bin"
  displayName: Add Conda to PATH

- script: 'pip install azureml-sdk'
  displayName: 'Prepare Conda Environment (using yml)'
  continueOnError: true
l

  
- script: 
     python scripts/generate_conda_file.py --gpu
  displayName: ' generate_conda_file.py'

- script: |
     more ./reco_gpu.yaml
  displayName: 'Print reco_gpu.yaml'

- script: |
     chmod +x scripts/*.py
     ls -al scripts
     chmod +x tests/AzureDevOpsConfig/*.py
     ls -al tests/AzureDevOpsConfig
  displayName: 'ls'

- script: |
     python --version
     pip install azure-cli==2.0.46
     pip install --upgrade azureml-sdk[cli]
     pip install -r tests/AzureDevOpsConfig/requirements.txt
  displayName: 'install cli'

#- script: |
#     source activate reco_gp && \
#     pytest tests/unit -m "not notebooks and not spark and not gpu" --junitxml=reports/test-unit.xml
#  displayName: ' Python Script'
  
#- bash: |
#    conda env list
#    source activate reco_gpu
#    pytest --version
#    python -c "import azureml.core; print("SDK version:", azureml.core.VERSION)"
#    pytest tests/unit/test_gpu_utils.py::test_get_number_gpus
#  displayName: 'unit tests'

- task: AzureCLI@1
  displayName: 'Create or get workspace'
  inputs:
    azureSubscription: 'AzureML Nursery (15ae9cb6-95c1-483d-a0e3-b1a1a3b06324)'
    scriptLocation: inlineScript
    inlineScript: 'python tests/AzureDevOpsConfig/00-WorkSpace.py'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-*.xml'
  inputs:
    testResultsFiles: '**/test-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()


